### PR TITLE
Take test fixes for 0.1 release branch, and prepare 0.1.2

### PR DESCRIPTION
**Pull request by ctz**
This is the tail end of #127, plus a version bump, plus test churn commits. That gets `cargo test` working for me locally. Let's see what CI thinks...

### CODE REVIEW

**Comment by complexspaces** [comment]
CI is definitely not happy with the outdated Android image and new* clippy lints 😢

**Comment by ctz** [comment]
> CI is definitely not happy with the outdated Android image and new* clippy lints 😢

lol, please excuse the noise while I determine the precise set of testing/infra commits  to cherry pick...

**Comment by ctz** [comment]
ok, whew. ready for review.

all but the final two commits are already on main.

**Comment by complexspaces** [comment]
FWIW in the future I can handle the bulk of `0.1` release work in the future since this branch exists almost solely for use at my employer and I don't want it to burden the other maintainers with that need.

I'll take a look at the changes here either way though 👍

**Review by complexspaces — APPROVED** [review]
This looks good to me. I sanity-checked the lockfile effects of this one internally at work and the result is clean 🎉.

I double checked the existing commits from `main` match what I'd expect as well, so LGTM.

**Comment by ctz** [comment]
Can I leave you to merge this and make the release?

**Comment by complexspaces** [comment]
Sure, I'd be happy to handle that. Thanks for getting the branch caught up in CI.

**Comment by complexspaces** [comment]
### Post-merge steps

- [ ] ~~Generate Android Maven artifacts locally~~ N/A, no Android changes.
- [x] Create and push Git tag
- [x] `cargo publish` for each required crate, based on release steps
- [x] Create companion GitHub release

**Pull request merged**
